name: amazon_clone
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.5
  provider: ^6.0.5
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  dotted_border: ^2.1.0
  charts_flutter: ^0.12.0
  file_picker: ^6.1.1
  cloudinary_public: ^0.23.1
  flutter_rating_bar: ^4.0.1
  fpdart: ^1.1.0
  pay: ^2.0.0
  phonepe_payment_sdk: ^2.0.1
  crypto: ^3.0.3
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  html: ^0.15.4
  flutter_spinkit: ^5.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  intl: ^0.18.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/applepay.json
   - assets/gpay.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
